### ISSUE TITLE
Vault parameter is missing

### ISSUE THREAD

**Issue by yurist38** [alexislepresle/gatsby-plugin-paypal#2]
Hello!
I see that the plugin doesn't use the `vault` query parameter when loading the Paypal SDK script. However, in the [docs](https://developer.paypal.com/docs/subscriptions/integrate/#4-create-a-subscription) it's said that this parameter must be `true` in case of subscription (its default value is `false`). Have you tested the plugin with subscriptions? Thanks!

**Comment by alexislepresle** [comment]
Hello @yurist38 ,

I just added the possibility to add the parameter vault. thanks for the issue. 
Npm version : gatsby-plugin-paypal@1.1.4

Tell me again if it's good for you.

Have a nice week-end :)

**Comment by yurist38** [comment]
Oh, great! This should work. Thank you very much for the change! And have a nice weekend too!
